/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ResolverBase, ResolverBaseInterface } from "../ResolverBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class ResolverBase__factory {
  static readonly abi = _abi;
  static createInterface(): ResolverBaseInterface {
    return new Interface(_abi) as ResolverBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ResolverBase {
    return new Contract(address, _abi, runner) as unknown as ResolverBase;
  }
}
